In [1]:
import sys
sys.dont_write_bytecode = True

# for debug print
def chkprint(*args):
    from inspect import currentframe
    names = {id(v):k for k,v in currentframe().f_back.f_locals.items()}
    print(', '.join(names.get(id(arg),'???')+' : '+str(type(arg))+' = '+repr(arg) for arg in args))

In [2]:
import numpy as np

In [3]:
# NumPy 配列初期化
a = np.array([1, 2, 3, 4, 5])
chkprint(a)
print(a)

a : <class 'numpy.ndarray'> = array([1, 2, 3, 4, 5])
[1 2 3 4 5]


In [4]:
# 二次元配列
b = np.array([[1, 2, 3], [4, 5, 6]])
chkprint(b)
print(b)

b : <class 'numpy.ndarray'> = array([[1, 2, 3],
       [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


In [5]:
# 配列初期化 (一気に)
print(np.zeros(10))
print(np.zeros((3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
# 1 で初期化
print(np.ones(10))
print(np.ones((3, 2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# 連番の配列
print(np.arange(5))
print(np.arange(2, 9))
print(np.arange(5, 8, 0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [8]:
# 行列計算
a = np.array([1, 2, 3, 4, 5])   #初期化
b = a * 2  #計算
print(b)

[ 2  4  6  8 10]


In [9]:
# 行列計算 (その２)
x = np.arange(10)
y = 3 * x + 5
print(y)

[ 5  8 11 14 17 20 23 26 29 32]


In [10]:
# NumPy 配列の次元数を調べる
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b.shape)

(2, 3)
(3, 3)


In [12]:
# NumPy で次元数を変換
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a=", a)
b = a.flatten()
print("b=", b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]


In [13]:
# reshape() メソッドを使用して配列の次元数を任意の形状に変換
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
# NumPy 配列の要素にアクセス
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = v[0]
b = v[1:]
c = v[: , 0]
print("a=", a)
print("b=", b)
print("c=", c)

a= [1 2 3]
b= [[4 5 6]
 [7 8 9]]
c= [1 4 7]
